// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations20540App.Models;

namespace Migrations20540App.Migrations
{
    [DbContext(typeof(s20540DbContext))]
    [Migration("20210430160657_AddedDataToMedicamentPrescription_MedicamentTables")]
    partial class AddedDataToMedicamentPrescription_MedicamentTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MigrationApps20540.Models.Prescription_Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .HasColumnType("int");

                    b.Property<int>("IdPrescription")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Dose")
                        .HasColumnType("int");

                    b.HasKey("IdMedicament", "IdPrescription");

                    b.HasIndex("IdPrescription");

                    b.ToTable("Prescription_Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            IdPrescription = 1,
                            Details = "Dzienie",
                            Dose = 20
                        },
                        new
                        {
                            IdMedicament = 2,
                            IdPrescription = 2,
                            Details = "Tygodniowo",
                            Dose = 3
                        },
                        new
                        {
                            IdMedicament = 3,
                            IdPrescription = 3,
                            Details = "Dziennie",
                            Dose = 4
                        });
                });

            modelBuilder.Entity("Migrations20540App.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDoctor");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            IdDoctor = 1,
                            Email = "cos@cos.pl",
                            FirstName = "Jakub",
                            LastName = "Komorowski"
                        },
                        new
                        {
                            IdDoctor = 2,
                            Email = "cos123@dsa.pl",
                            FirstName = "Magda",
                            LastName = "Romanowska"
                        },
                        new
                        {
                            IdDoctor = 3,
                            Email = "kotek123@cdass.pl",
                            FirstName = "Marysia",
                            LastName = "Wasilewska"
                        });
                });

            modelBuilder.Entity("Migrations20540App.Models.Medicament", b =>
                {
                    b.Property<int>("IdMedicament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descritpion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMedicament");

                    b.ToTable("Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            Descritpion = "tabletka laktoza",
                            Name = "Rutinoscorbin",
                            Type = "AAA"
                        },
                        new
                        {
                            IdMedicament = 2,
                            Descritpion = "Alergicy są grupa narazona na wzmozona sennosc",
                            Name = "Claritine",
                            Type = "BBB"
                        },
                        new
                        {
                            IdMedicament = 3,
                            Descritpion = "Tabletka powlekana Ibuprom zawiera 200 mg ibuprofenu.",
                            Name = "Ibuprom",
                            Type = "CCC"
                        });
                });

            modelBuilder.Entity("Migrations20540App.Models.Patient", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPatient");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            IdPatient = 1,
                            BirthDate = new DateTime(2000, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            FirstName = "Ala",
                            LastName = "Chryniecka"
                        },
                        new
                        {
                            IdPatient = 2,
                            BirthDate = new DateTime(1999, 5, 26, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            FirstName = "Tomasz",
                            LastName = "Tolak"
                        },
                        new
                        {
                            IdPatient = 3,
                            BirthDate = new DateTime(2001, 11, 6, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            FirstName = "Katarzyna",
                            LastName = "Mykhalkiv"
                        });
                });

            modelBuilder.Entity("Migrations20540App.Models.Prescription", b =>
                {
                    b.Property<int>("IdPrescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdPatient")
                        .HasColumnType("int");

                    b.HasKey("IdPrescription");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdPatient");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            IdPrescription = 1,
                            Date = new DateTime(2019, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            IdDoctor = 1,
                            IdPatient = 1
                        },
                        new
                        {
                            IdPrescription = 2,
                            Date = new DateTime(2015, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2016, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            IdDoctor = 2,
                            IdPatient = 2
                        },
                        new
                        {
                            IdPrescription = 3,
                            Date = new DateTime(2020, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2001, 12, 31, 5, 10, 20, 0, DateTimeKind.Unspecified),
                            IdDoctor = 3,
                            IdPatient = 3
                        });
                });

            modelBuilder.Entity("MigrationApps20540.Models.Prescription_Medicament", b =>
                {
                    b.HasOne("Migrations20540App.Models.Medicament", "Medicament")
                        .WithMany("Prescription_Medicaments")
                        .HasForeignKey("IdMedicament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Migrations20540App.Models.Prescription", "Prescription")
                        .WithMany("Prescription_Medicaments")
                        .HasForeignKey("IdPrescription")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicament");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Migrations20540App.Models.Prescription", b =>
                {
                    b.HasOne("Migrations20540App.Models.Doctor", "Doctor")
                        .WithMany("DoctorPrescriptions")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Migrations20540App.Models.Patient", "Patient")
                        .WithMany("PatientPrescriptions")
                        .HasForeignKey("IdPatient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Migrations20540App.Models.Doctor", b =>
                {
                    b.Navigation("DoctorPrescriptions");
                });

            modelBuilder.Entity("Migrations20540App.Models.Medicament", b =>
                {
                    b.Navigation("Prescription_Medicaments");
                });

            modelBuilder.Entity("Migrations20540App.Models.Patient", b =>
                {
                    b.Navigation("PatientPrescriptions");
                });

            modelBuilder.Entity("Migrations20540App.Models.Prescription", b =>
                {
                    b.Navigation("Prescription_Medicaments");
                });
#pragma warning restore 612, 618
        }
    }
}
